"use client";

import { useActionState } from "react";
import Link from "next/link";
import { format } from "date-fns";
import {
  ArrowLeftIcon,
  BadgeCheckIcon,
  Building2Icon,
  CoinsIcon,
  GraduationCapIcon,
  MailIcon,
  MapPinIcon,
  PhoneIcon,
  PlusIcon,
  ShieldCheckIcon,
  UserRoundIcon,
  UsersIcon,
} from "lucide-react";

import { setSchoolVerificationAction } from "@/app/super/actions";
import { topupWalletAction } from "@/app/super/actions";
import type { ActionState } from "@/app/admin/actions";
import type { SchoolDoc, UserDoc, WalletDoc } from "@/types/firestore";
import type { Serialized, SerializedWithId } from "@/lib/serialize";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Field, FieldGroup, FieldLabel } from "@/components/ui/field";
import { Input } from "@/components/ui/input";
import { KpiCard } from "@/components/features/dashboard/charts";
import { VerifiedBadge } from "@/components/features/school/verified-badge";
import { useActionToast } from "@/components/features/super/schools-manager";
import { formatTokens, formatUgx, formatUsd, tokensToUsd, usdToUgx } from "@/lib/pricing";

interface SchoolDetailProps {
  school: SerializedWithId<SchoolDoc>;
  admins: SerializedWithId<UserDoc>[];
  teachers: SerializedWithId<UserDoc>[];
  students: SerializedWithId<UserDoc>[];
  wallet: Serialized<WalletDoc> | null;
  examCount: number;
  attemptCount: number;
}

/** Super-admin, full-control view of one school. */
export function SuperSchoolDetailView({
  school,
  admins,
  teachers,
  students,
  wallet,
  examCount,
  attemptCount,
}: SchoolDetailProps) {
  const [verifyState, verifyAction, verifyPending] = useActionState<ActionState | null, FormData>(
    setSchoolVerificationAction,
    null,
  );
  useActionToast(verifyState, undefined, school.verification === "verified" ? "Blue tick revoked" : "School verified");

  return (
    <div className="flex flex-col gap-6">
      <Button
        variant="ghost"
        size="sm"
        className="text-muted-foreground hover:text-foreground -ml-2 gap-1.5 font-medium"
        render={<Link href="/super/schools" />}
      >
        <ArrowLeftIcon className="size-4" />
        <span>Back to schools</span>
      </Button>

      {/* Header */}
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div className="flex items-center gap-4">
          <span className="bg-brand text-primary-foreground flex size-12 items-center justify-center rounded-2xl shadow-md">
            <Building2Icon className="size-6" />
          </span>
          <div>
            <h1 className="flex items-center gap-2 text-xl font-semibold tracking-tight">
              {school.name}
              <VerifiedBadge status={school.verification} size="md" />
            </h1>
            <p className="text-muted-foreground text-sm capitalize">
              {school.level ?? "—"} school · created{" "}
              {school.createdAt ? format(new Date(school.createdAt as unknown as string), "d MMM yyyy") : "—"}
            </p>
          </div>
        </div>
        <form action={verifyAction}>
          <input type="hidden" name="schoolId" value={school.id} />
          <input type="hidden" name="status" value={school.verification === "verified" ? "unverified" : "verified"} />
          <Button
            type="submit"
            size="sm"
            variant={school.verification === "verified" ? "outline" : "default"}
            disabled={verifyPending}
            className="shadow-glow"
          >
            <BadgeCheckIcon data-icon="inline-start" />
            {verifyPending
              ? "Saving…"
              : school.verification === "verified"
                ? "Revoke blue tick"
                : "Grant blue tick"}
          </Button>
        </form>
      </div>

      {/* KPIs */}
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">
        <KpiCard title="Students" value={school.studentCount ?? students.length} />
        <KpiCard title="Teachers" value={school.teacherCount ?? teachers.length} />
        <KpiCard title="Admins" value={school.adminCount ?? admins.length} />
        <KpiCard title="Exams" value={examCount} hint="Generated by this school" />
        <KpiCard title="Exam attempts" value={attemptCount} hint="All time" accent />
      </div>

      <div className="grid gap-4 lg:grid-cols-3">
        {/* Profile */}
        <Card className="shadow-card lg:col-span-2">
          <CardHeader>
            <CardTitle>School profile</CardTitle>
            <CardDescription>
              Details the school provided — the basis for the blue-tick decision.
            </CardDescription>
          </CardHeader>
          <CardContent className="grid gap-4 sm:grid-cols-2">
            <InfoRow icon={<MailIcon className="size-3.5" />} label="Email" value={school.email} />
            <InfoRow icon={<PhoneIcon className="size-3.5" />} label="Phone" value={school.phone} />
            <InfoRow icon={<MapPinIcon className="size-3.5" />} label="Address" value={school.address} />
            <InfoRow
              icon={<ShieldCheckIcon className="size-3.5" />}
              label="Registration / EMIS"
              value={school.registrationNumber}
            />
            <div className="sm:col-span-2">
              <p className="text-muted-foreground text-xs font-medium tracking-wide uppercase">Motto</p>
              <p className="text-sm">{school.motto ?? "—"}</p>
            </div>
            {school.description && (
              <div className="sm:col-span-2">
                <p className="text-muted-foreground text-xs font-medium tracking-wide uppercase">Description</p>
                <p className="text-sm">{school.description}</p>
              </div>
            )}
          </CardContent>
        </Card>

        {/* Wallet */}
        <Card className="shadow-card">
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <CoinsIcon className="size-4" /> School wallet
            </CardTitle>
            <CardDescription>Pay-as-you-go balance and lifetime usage.</CardDescription>
          </CardHeader>
          <CardContent className="flex flex-col gap-4">
            <div>
              <p className="text-2xl font-semibold tabular-nums">
                {formatTokens(wallet?.balanceTokens ?? 0)}
              </p>
              <p className="text-muted-foreground text-xs">tokens available</p>
            </div>
            <div className="grid grid-cols-2 gap-3 text-sm">
              <div>
                <p className="text-muted-foreground text-xs">Consumed</p>
                <p className="font-medium tabular-nums">
                  {formatTokens(wallet?.totalConsumedTokens ?? 0)}
                </p>
              </div>
              <div>
                <p className="text-muted-foreground text-xs">Topped up</p>
                <p className="font-medium tabular-nums">{formatTokens(wallet?.totalTopupTokens ?? 0)}</p>
              </div>
            </div>
            <TopupDialog walletId={school.id} schoolName={school.name} />
          </CardContent>
        </Card>
      </div>

      {/* Staff */}
      <div className="grid gap-4 lg:grid-cols-2">
        <StaffCard
          title="Admins"
          icon={<ShieldCheckIcon className="size-4" />}
          people={admins}
          emptyText="No admins — the owner acts as one."
        />
        <StaffCard
          title="Teachers"
          icon={<UserRoundIcon className="size-4" />}
          people={teachers}
          emptyText="No teachers yet."
          linkBase="/super/teachers"
        />
      </div>

      {/* Students */}
      <Card className="shadow-card">
        <CardHeader className="flex flex-row items-start justify-between space-y-0">
          <div className="flex flex-col gap-1.5">
            <CardTitle className="flex items-center gap-2">
              <UsersIcon className="size-4" /> Students
            </CardTitle>
            <CardDescription>
              Most recent {students.length} of {school.studentCount ?? students.length} — open one for
              the full profile and performance.
            </CardDescription>
          </div>
          <Button variant="outline" size="sm" render={<Link href={`/super/students?school=${school.id}`} />}>
            <GraduationCapIcon data-icon="inline-start" className="size-4" />
            All students
          </Button>
        </CardHeader>
        <CardContent className="p-0">
          {students.length === 0 ? (
            <p className="text-muted-foreground p-8 text-center text-sm">No students enrolled yet.</p>
          ) : (
            <div className="divide-y">
              {students.slice(0, 10).map((st) => (
                <Link
                  key={st.id}
                  href={`/super/students/${st.id}`}
                  className="hover:bg-accent/40 flex items-center justify-between gap-3 px-6 py-3"
                >
                  <div className="min-w-0">
                    <p className="truncate text-sm font-medium">{st.displayName}</p>
                    <p className="text-muted-foreground text-xs">{st.email}</p>
                  </div>
                  <div className="flex items-center gap-2">
                    {st.classLevel && (
                      <Badge variant="outline">
                        {st.level === "primary" ? "P" : "S"}
                        {st.classLevel}
                      </Badge>
                    )}
                    <Badge variant="outline" className="capitalize">
                      {st.status}
                    </Badge>
                  </div>
                </Link>
              ))}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}

function InfoRow({
  icon,
  label,
  value,
}: {
  icon: React.ReactNode;
  label: string;
  value: string | null | undefined;
}) {
  return (
    <div>
      <p className="text-muted-foreground flex items-center gap-1.5 text-xs font-medium tracking-wide uppercase">
        {icon}
        {label}
      </p>
      <p className="mt-0.5 text-sm">{value?.trim() || "—"}</p>
    </div>
  );
}

function StaffCard({
  title,
  icon,
  people,
  emptyText,
  linkBase,
}: {
  title: string;
  icon: React.ReactNode;
  people: SerializedWithId<UserDoc>[];
  emptyText: string;
  linkBase?: string;
}) {
  return (
    <Card className="shadow-card">
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          {icon}
          {title} ({people.length})
        </CardTitle>
      </CardHeader>
      <CardContent className="p-0">
        {people.length === 0 ? (
          <p className="text-muted-foreground p-6 text-sm">{emptyText}</p>
        ) : (
          <div className="divide-y">
            {people.map((p) => {
              const content = (
                <div className="flex items-center justify-between gap-3 px-6 py-3">
                  <div className="min-w-0">
                    <p className="truncate text-sm font-medium">{p.displayName}</p>
                    <p className="text-muted-foreground text-xs">{p.email}</p>
                  </div>
                  <Badge
                    variant="outline"
                    className={
                      p.status === "active"
                        ? "border-emerald-500/30 bg-emerald-500/10 text-emerald-700 dark:text-emerald-400"
                        : ""
                    }
                  >
                    {p.status}
                  </Badge>
                </div>
              );
              return linkBase ? (
                <Link key={p.id} href={`${linkBase}/${p.id}`} className="hover:bg-accent/40 block">
                  {content}
                </Link>
              ) : (
                <div key={p.id}>{content}</div>
              );
            })}
          </div>
        )}
      </CardContent>
    </Card>
  );
}

/** Super-admin manual wallet top-up (billing continues until gateways ship). */
function TopupDialog({ walletId, schoolName }: { walletId: string; schoolName: string }) {
  const [state, formAction, pending] = useActionState<ActionState | null, FormData>(
    topupWalletAction,
    null,
  );
  useActionToast(state, undefined, "Wallet topped up");

  return (
    <Dialog>
      <DialogTrigger render={<Button className="shadow-glow" />}>
        <PlusIcon data-icon="inline-start" />
        Add credit
      </DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Top up {schoolName}</DialogTitle>
          <DialogDescription>
            Manually credit tokens. Rate: $0.027 / 1,000 tokens —{" "}
            {formatUgx(usdToUgx(tokensToUsd(100_000)))} per 100k.
          </DialogDescription>
        </DialogHeader>
        <form action={formAction}>
          <FieldGroup>
            <input type="hidden" name="walletId" value={walletId} />
            <Field>
              <FieldLabel htmlFor="tokens">Tokens</FieldLabel>
              <Input id="tokens" name="tokens" type="number" min={1000} required defaultValue={100000} />
            </Field>
            <p className="text-muted-foreground text-xs">
              100,000 → {formatUsd(tokensToUsd(100_000))} · 1,000,000 →{" "}
              {formatUsd(tokensToUsd(1_000_000))}
            </p>
            <DialogFooter>
              <Button type="submit" disabled={pending}>
                {pending ? "Crediting…" : "Credit wallet"}
              </Button>
            </DialogFooter>
          </FieldGroup>
        </form>
      </DialogContent>
    </Dialog>
  );
}
